# Reverse Windows RDP for GitHub Actions
# This YAML establishes the "build" workflow where we will execute all required scripts
# During the process, it should get stuck at the last step where it creates a new tunnel on ngrok.

name: Windows
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Preparing environment...
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        run: |
          # Download ngrok and set up the authentication token
          Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          # Force overwriting existing files when extracting ngrok
          Expand-Archive -LiteralPath '.\ngrok.zip' -DestinationPath '.' -Force
          ./ngrok/ngrok.exe authtoken $env:NGROK_AUTH_TOKEN

      - name: Start ngrok tunnel
        run: |
          Start-Process -NoNewWindow -FilePath './ngrok/ngrok.exe' -ArgumentList 'tcp 3389'
          # Wacht tot de tunnel actief is
          Start-Sleep -Seconds 5

      - name: Configure environment
        run: ./configure.ps1 
