# Reverse Windows RDP for GitHub Actions
# This YAML establishes the "build" workflow where we will execute all required scripts
# During the process, it should get stuck at the last step where it creates a new tunnel on ngrok.

name: Windows
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Preparing environment...
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        run: |
          # Download ngrok and set up the authentication token
          $ngrokZipPath = "ngrok.zip"
          $ngrokPath = "ngrok"

          # Download ngrok
          Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile $ngrokZipPath
          
          # Force overwriting existing files when extracting ngrok
          Expand-Archive -LiteralPath $ngrokZipPath -DestinationPath '.' -Force
          
          # Check the contents of the current directory
          Get-ChildItem -Recurse
          
          # Check if ngrok executable exists
          if (Test-Path "$ngrok/ngrok.exe") {
              # Set up the ngrok authtoken
              Start-Process -FilePath "$ngrok/ngrok.exe" -ArgumentList "authtoken $env:NGROK_AUTH_TOKEN" -NoNewWindow -Wait
          } else {
              Write-Error "Ngrok executable not found at the expected path."
              Exit 1
          }

      - name: Start ngrok tunnel
        run: |
          Start-Process -NoNewWindow -FilePath './ngrok/ngrok.exe' -ArgumentList 'tcp 3389'
          # Wacht tot de tunnel actief is
          Start-Sleep -Seconds 5

      - name: Configure environment
        run: ./configure.ps1 
