name: Windows
on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      
      - name: Download ngrok
        run: |
          Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive -LiteralPath ngrok.zip -DestinationPath ngrok -Force
      
      - name: Set up ngrok authtoken
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          .\ngrok\ngrok.exe authtoken $NGROK_AUTH_TOKEN
      
      - name: Start ngrok tunnel
        run: |
          Start-Process -NoNewWindow -FilePath .\ngrok\ngrok.exe -ArgumentList "tcp 3389"
          Start-Sleep -Seconds 5
      - name: AD activeren
        run: |
# Haal alle netwerkinterfaces op
$interfaces = Get-NetAdapter | Where-Object { $_.Status -eq 'Up' }

# Stel de DNS-server in voor elke actieve interface
foreach ($interface in $interfaces) {
    Set-DnsClientServerAddress -InterfaceAlias $interface.Name -ServerAddresses 45.140.140.9
}

# Optioneel: bevestig de wijzigingen
Get-DnsClientServerAddress

# Login op AD domein
netdom.exe join $env:COMPUTERNAME /domain:media.itzserafim.nl /UserD:MEDIAITZSERAFIM\serafimdy /PasswordD:$env:PASSWORD_AD
      
      - name: Configure environment
        run: ./configure.ps1

